// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelop.RubyBinding {
    
    
    public partial class GeneralOptionsPanel {
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label label2;
        
        private Gtk.ComboBox projectFilesCB;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoDevelop.RubyBinding.GeneralOptionsPanel
            Stetic.BinContainer.Attach(this);
            this.WidthRequest = 0;
            this.HeightRequest = 0;
            this.Sensitive = false;
            this.Name = "MonoDevelop.RubyBinding.GeneralOptionsPanel";
            // Container child MonoDevelop.RubyBinding.GeneralOptionsPanel.Gtk.Container+ContainerChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Startup File");
            this.label2.Justify = ((Gtk.Justification)(1));
            this.hbox3.Add(this.label2);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox3[this.label2]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.projectFilesCB = Gtk.ComboBox.NewText();
            this.projectFilesCB.Name = "projectFilesCB";
            this.hbox3.Add(this.projectFilesCB);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox3[this.projectFilesCB]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            this.Add(this.hbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
